name: Build and release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-matrix:
    strategy:
      matrix:
        build-os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        include:
          - build-os: "ubuntu-latest"
            archive-name: "sonix-flasher-go_linux.tar.gz"
            archive-cmd: |
                          chmod +x sonix-flasher-go
                          tar -cvzf sonix-flasher-go_linux.tar.gz sonix-flasher-go

          - build-os: "windows-latest"
            archive-name: "sonix-flasher-go_windows.zip"
            archive-cmd: powershell Compress-Archive sonix-flasher-go.exe sonix-flasher-go_windows.zip

          - build-os: "macos-latest"
            archive-name: "sonix-flasher-go_mac.zip"
            archive-cmd: |
                          chmod +x sonix-flasher-go
                          zip -r sonix-flasher-go_mac.zip sonix-flasher-go

    runs-on: ${{ matrix.build-os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Go build ${{ matrix.build-os }}
        run: go build -ldflags "-w -s" .
      
      - name: Compress
        run: ${{ matrix.archive-cmd }}
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ${{ matrix.archive-name }}

  # create release
  release:
    needs: build-matrix
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2

      - name: Generate changelog
        run: awk '/^## / {if (p) {exit}; {p=1}} p' CHANGELOG.md > latest-CHANGELOG.md

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: latest-CHANGELOG.md
          files: build/*
